### ISSUE TITLE
Add matchMedia polyfill back in as optional dependency

### ISSUE THREAD

**Issue by trabus** [AVCEngineering/ember-cli-responsive#3]
Unfortunately, many people still need to support IE8 and IE9. I'd recommend adding the matchMedia polyfill back in as an optional dependency, or at least mention it in the docs to prevent confusion over why their app is breaking in browsers that don't support matchMedia.

**Comment by jkatsnelson** [comment]
One of my teammates just went chasing down why the app broke in IE9, because I accidentally merged this library in without the polyfill fix...even though I saw that it existed.

I would be happy to submit a PR that changes the polyfill to be opt-out instead of opting in via an explicit import in the Brocfile. Maybe help dummy-proof this library for people like me :)

**Comment by AVCEngineering** [comment]
The ember-cli-responsive generator will pull the matchMedia bower depedency. This was intentionally left optional for those that don't require legacy support. Just include matchMedia in your brocfile:

``` js
app.import('bower_components/matchMedia/matchMedia.js');
```

**Comment by jkatsnelson** [comment]
Yep yep, i know that, and already did it succesfully -- your documentation lays it out simply -- my comment suggests making it opt out instead of opt in.

**Comment by AVCEngineering** [comment]
Ah my bad! I'd still be in favour of opt-out as I'm not a fan of including unnecessary code in the js payload. Feel free to create a fork though
